name: Build and Deploy

on:
  push:
    branches:
      - main  # Set this to the branch you use for production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Replace this with your required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build  # Replace or confirm this is your build command

    # Add steps for deployment
    - name: Deploy
      run: echo "Add your deployment commands here"
