name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you use for production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Replace this with your required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build  # Replace or confirm this is your build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Set this to the directory where your build outputs the files to be deployed
